### ISSUE TITLE
Callback for when a button is held down?

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hammerspoon_asm.undocumented#9]
@asmagill - I know this is probably very low on your priority list, but it would be awesome if there was some way for `hs._asm.undocumented.touchbar` to trigger a different callback if a button is held down (as opposed to being pressed once) - like a "repeat" function in other Hammerspoon modules. Possible?

**Comment by asmagill** [comment]
Off the top of my head, I'm not sure. I've noticed that there are a couple of new item types with 10.15 that I need to look at, and at least a few that I hadn't implemented yet, so its possible one or more of the updates may make this trivial.

If not, it may also be possible to do something like we do for `hs.hotkey` where we setup our own timer to handle repeats because we are guaranteed a separate release event that we can use to disable the timer with, so... if we can reliably get both the "down" and "up" for a touchbar item, this should be doable even if the Apple API doesn't explicitly support it.

My priorities at the moment (not necessarily in any specific order) are finishing `hs.text`, cleaning up `hs._asm.axuielement` so it can become `hs.axuielement`, and getting the touchbar working on 16" laptops... after those, I'll see about extending touchbar. Prompt me with a reminder then, if this is still an important addition to investigate.

**Comment by latenitefilms** [comment]
I'm going to close this issue for now, as it's not really a priority. We can re-evaluate later down the line if/when this extensions finds its way into Hammerspoon.
